#!/usr/bin/env bash


# get_file() <filepath>
#
# Gets the content from a file at the given <filepath>
function get_file() {
    local -r filepath="${1:?get_file() called but no filepath passed in!}"
    
    if file_exists "${filepath}"; then
        local content
        { IFS= read -rd '' content <"${filepath}";}  2>/dev/null
        printf '%s' "${content}"
    else
        return 1
    fi
}

MODEL="${MODEL:-o3-mini}"
EDITOR_MODEL="${EDITOR_MODEL:-sonnet}"
REASONING="${REASONING:-high}"

# has_command <cmd>
#
# checks whether a particular program passed in via $1 is installed 
# on the OS or not (at least within the $PATH)
function has_command() {
    local -r cmd="${1:?cmd is missing}"

    if command -v "${cmd}" &> /dev/null; then
        return 0
    else 
        return 1
    fi
}


function chat() {
    local -r prompt="${1:?no prompt passed into chat!}"
    local -r CONTEXT="$(get_file "./scripts/context.md")"

    if [[ -z "${CONTEXT}" ]]; then
        echo "Context not found!"
        exit 1;
    fi

    if has_command "aider"; then

        echo "Starting ..."
        echo "Starting ..."

        aider --model "${MODEL}" --architect --reasoning-effort "${REASONING}" --editor-model "${EDITOR_MODEL}" --no-detect-urls --no-auto-commit --yes-always --file "src/cli/cli-types.ts" --file 'src/type-guards/*.ts' --file "src/ast/symbol-ast-types.ts" --file "src/ast/testing-types.ts" --file "src/ast/file-ast-types.ts" --message "${CONTEXT}${prompt}"
        aider --model "${MODEL}" --architect --reasoning-effort "${REASONING}" --editor-model "${EDITOR_MODEL}" --no-detect-urls --no-auto-commit --yes-always --file "src/cli/cli-types.ts" --file 'src/type-guards/*.ts' --file "src/ast/symbol-ast-types.ts" --file "src/ast/testing-types.ts" --file "src/ast/file-ast-types.ts" --message "${CONTEXT}${prompt}"

    else 
        echo "- you don\'t have the aider assistant installed"
        echo "- this is a requirement for running this chat prompt"
        echo ""
        echo "- install aider and then rerun"
    fi
}

chat "${@}"
