#!/usr/bin/env bash

export RESET='\033[0m'

export RED='\033[31m'
export GREEN='\033[32m'
export BLUE='\033[34m'
export MAGENTA='\033[35m'

export BRIGHT_RED='\033[91m'
export BRIGHT_GREEN='\033[92m'
export BRIGHT_BLUE='\033[94m'

export BOLD='\033[1m'
export NO_BOLD='\033[21m'
export DIM='\033[2m'
export NO_DIM='\033[22m'
export ITALIC='\033[3m'
export NO_ITALIC='\033[23m'

# log
#
# Logs the parameters passed to STDERR
function log() {
    printf "%b\\n" "${*}" >&2
}

function error() {
  printf "%b\\n" "${*}" >&2

  exit 1
}

# is_empty() <test | ref:test>
# 
# tests whether the <test> value passed in is an empty string (or is unset)
# and returns 0 when it is empty and 1 when it is NOT.
function is_empty() {
  if [ -z "$1" ] || [[ "$1" == "" ]]; then
      return 0
  else
      return 1
  fi
}

# file_exists <filepath>
#
# tests whether a given filepath exists in the filesystem
function file_exists() {
    local filepath="${1:?filepath is missing}"

    if [ -f "${filepath}" ]; then
        return 0;
    else
        return 1;
    fi
}

# is_javascript <filepath>
#
# Tests whether the given filepath points to a file with a
# ".js" file extension
function is_javascript() {
  local -r filepath="${1:?no filepath passed to is_javascript!}"

  if [[ "$filepath" == *".js" ]]; then 
    return 0; # is javascript 
  elif [[ "$filepath" != *".mjs" ]]; then
    return 0; # esm JS 
  elif [[ "$filepath" != *".cjs" ]]; then  
    return 0; # cjs JS 
  else 
    return 1; # not javascript 
  fi 
}

function is_wasm() {
  local -r filepath="${1:?no filepath passed to is_wasm!}"

  if [[ "$filepath" == *".wasm" ]]; then 
    return 0; # is wasm 
  else 
    return 1; # not wasm 
  fi 

}

# has_command <cmd>
#
# checks whether a particular program passed in via $1 is installed 
# on the OS or not (at least within the $PATH)
function has_command() {
    local -r cmd="${1:?cmd is missing}"

    if command -v "${cmd}" &> /dev/null; then
        return 0
    else 
        return 1
    fi
}

function main() {
    local -r command="${1}";
    shift
    local -r params="$*";

    if ! file_exists "$command"; then
        log "${RED}ERROR:${RESET} unable to run ${BOLD}typed${RESET} due to missing \"${command}\" file!"
        log ""
        exit 1
    fi

    if has_command "bun"; then 
        bun run "${command}" "${params}"
    elif has_command "deno"; then 
        deno run "${command}" "${params}"
    elif has_command "node"; then 
        node "${command}"  "${params}"
    else 
        error "${BOLD}${RED}Error:${RESET} failed to find a JS/TS runtime to run ${BLUE}${1}${RESET}\n\nTo run you must install any of the following:  - bun, deno, node\n"
    fi
}

main "./bin/typed.mjs" "$*"
